[package]
name = "binjs"
version = "0.3.0"
authors = ["David Teller <D.O.Teller@gmail.com>"]

[features]
default = []

[dependencies]
binjs_generic = { path = "crates/binjs_generic", version = "*" }
binjs_es6 = { path = "crates/binjs_es6", version = "*" }
binjs_io = { path = "crates/binjs_io", version = "*" }
binjs_meta = { path = "crates/binjs_meta", version = "*" }
binjs_shared = { path = "crates/binjs_shared", version = "*" }
assert_matches = "*"
brotli = "1.*"
env_logger = "^0.5"
flate2 = "0.2"
Inflector = "^0.11.2"
itertools = "*"
json = "*"
log = "*"
lzw = "*"
rand = "*"
topological-sort = "*"
vec_map = "*"

[dev-dependencies]
clap = "*"
env_logger = "*"
glob = "*"
test-logger = "*"
webidl = "*"
yaml-rust = "*"
