[package]
name = "binjs"
version = "0.2.0"
authors = ["David Teller <D.O.Teller@gmail.com>"]

[features]
default = []
# If specified, build support for using SpiderMonkey as a parser.
spidermonkey = []
esprima = []

[dependencies]
assert_matches = "*"
brotli = "1.*"
env_logger = "*"
flate2 = "0.2"
json = "*"
log = "*"
lzw = "*"
rand = "*"
topological-sort = "*"
vec_map = "*"

[dev-dependencies]
clap = "*"
env_logger = "*"
glob = "*"
test-logger = "*"
