[package]
name = "binjs"
version = "0.3.0"
authors = ["David Teller <D.O.Teller@gmail.com>"]

[features]
default = []

[dependencies]
assert_matches = "*"
brotli = "1.*"
env_logger = "^0.5"
flate2 = "0.2"
Inflector = { path = "../blurbs/Inflector" }
itertools = "*"
json = "*"
log = "*"
lzw = "*"
rand = "*"
topological-sort = "*"
vec_map = "*"
webidl = "*"

[dev-dependencies]
clap = "*"
env_logger = "*"
glob = "*"
test-logger = "*"
yaml-rust = "^0.4"
