[package]
name = "binjs"
version = "0.1.0"
authors = ["David Teller <D.O.Teller@gmail.com>"]

[features]
default = []
# If specified build with SpiderMonkey.
spidermonkey = []

[dependencies]
env_logger = "*"
log ="*"
serde_json = "1.0"
assert_matches = "*"

[dev-dependencies]
env_logger = "*"
glob = "*"
test-logger = "*"
