[package]
name = "binjs_io"
version = "0.1.0"
authors = ["David Teller <D.O.Teller@gmail.com>"]

[dependencies]
brotli = "*"
flate2 = "^1.0"
itertools = "*"
lzw = "*"
log = "*"
priority-queue = "*"
rand = "*"
vec_map = "*"

[dev-dependencies]
env_logger = "*"
assert_matches = "*"
