[package]
name = "binjs_io"
version = "0.1.0"
authors = ["David Teller <D.O.Teller@gmail.com>"]

[dependencies]
# brotli = "*"
# Latest release of brotli is incompatible with Rust Nightly.
brotli = { git = "https://github.com/dropbox/rust-brotli", commit = "ae6d9d2db756e41af37f5164f0b5dec65c4c0825" }
flate2 = "^1.0"
lzw = "*"
log = "*"
rand = "^0.4"
vec_map = "*"

[dev-dependencies]
env_logger = "*"
assert_matches = "*"
