[package]
name = "binjs_io"
version = "0.2.0"
authors = ["David Teller <D.O.Teller@gmail.com>"]

[dependencies]
binjs_shared = { path = "../binjs_shared", version = "*" }
brotli = "*"
flate2 = "^1.0"
itertools = "*"
lzw = "*"
log = "*"
priority-queue = "*"
rand = "*"
vec_map = "*"
xml-rs = "*"

[dev-dependencies]
env_logger = "*"
assert_matches = "*"
